### PR TITLE
use php 5.3 array notation: array() instead of []

### PR DESCRIPTION
**Pull request by gicque**
ensuring compatibility with php 5.3

### CODE REVIEW

**Comment by namaless** [comment]
Bad idea for me, php 5.3 it's really old now, and EOL for 5.5 nearly so no sense to change the array annotation, the best way is update composer.json and put new php version inside.

**Comment by gicque** [comment]
since MongoLite do not use any new fonctionality not supported by PHP 5.3 except for the new array notation, i don't see why it would be a bad idea, more people would be able to use it without costing anything for the others.

**Comment by namaless** [comment]
@gicque all cheap hosting have php 5.4. One my client have a very cheap hosting (6 dollars / year) and have php 5.6 :)

**Comment by gicque** [comment]
@namaless absolutely, but there are some people who can't use anything but PHP 5.3, and my PR doesn't do anything against PHP 5.4+ it just makes sure that users of PHP5.3+ can use this package :)

**Comment by aheinze** [comment]
thank you for the contribution, but php 5.3 is dead. I don't want to have legacy code in the codebase just because of php 5.3 support.

**Pull request closed without merging**
